---
parameters:
  - name:             STACK_VERSION
    displayName:      component version
    type:             string
    default:          1.4.1

  - name:             feature_a
    displayName:      feature A
    type:             boolean
    default:          true

  - name:             feature_b
    displayName:      feature B
    type:             boolean
    default:          true

  - name:             feature_c
    displayName:      feature C
    type:             boolean
    default:          true


pool:
  vmImage:            ubuntu-latest

resources:
  - repo:             self

trigger:              none

name:                 "$(BuildID) sftp version ${{ parameters.SCF_SFTP_VERSION }}"
stages:
  - template:          pipelines/debug.yaml
    parameters:
      stageName:       Debug
